use crate::pasteboard_runtime::PasteboardSnapshot;
use atools_core::PasteboardItemKind;
use objc2::rc::autoreleasepool;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardTypeFileURL, NSPasteboardTypeHTML, NSPasteboardTypePDF,
    NSPasteboardTypePNG, NSPasteboardTypeRTF, NSPasteboardTypeRTFD, NSPasteboardTypeString,
    NSPasteboardTypeTIFF,
};
use objc2_foundation::{NSData, NSString};

const SOURCE_TYPE: &str = "org.nspasteboard.source";
const TRANSIENT_TYPES: &[&str] = &[
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];
const CONCEALED_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "com.agilebits.onepassword",
];

pub fn general_pasteboard_change_count() -> isize {
    autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount())
}

pub fn write_general_pasteboard_blob(media_type: &str, bytes: &[u8]) -> Result<(), String> {
    autoreleasepool(|_| {
        let pasteboard_type = match media_type {
            "application/pdf" => unsafe { NSPasteboardTypePDF },
            "image/png" => unsafe { NSPasteboardTypePNG },
            "image/tiff" => unsafe { NSPasteboardTypeTIFF },
            "text/rtf" => unsafe { NSPasteboardTypeRTF },
            "text/rtfd" => unsafe { NSPasteboardTypeRTFD },
            _ => return Err(format!("Unsupported PasteboardPro blob type: {media_type}")),
        };
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();
        let data = NSData::with_bytes(bytes);
        if pasteboard.setData_forType(Some(&data), pasteboard_type) {
            Ok(())
        } else {
            Err("macOS rejected the PasteboardPro blob payload".to_string())
        }
    })
}

pub fn write_general_pasteboard_html(
    html: &str,
    fallback_text: Option<&str>,
) -> Result<(), String> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        pasteboard.clearContents();
        let html = NSString::from_str(html);
        let wrote_html = pasteboard.setString_forType(&html, unsafe { NSPasteboardTypeHTML });
        let wrote_text = fallback_text.map_or(true, |text| {
            let text = NSString::from_str(text);
            pasteboard.setString_forType(&text, unsafe { NSPasteboardTypeString })
        });
        if wrote_html && wrote_text {
            Ok(())
        } else {
            Err("macOS rejected the PasteboardPro HTML payload".to_string())
        }
    })
}

pub fn read_general_pasteboard(
    previous_change_count: Option<isize>,
) -> Result<Option<(isize, PasteboardSnapshot)>, String> {
    autoreleasepool(|_| {
        let pasteboard = NSPasteboard::generalPasteboard();
        let change_count = pasteboard.changeCount();
        if previous_change_count == Some(change_count) {
            return Ok(None);
        }

        let type_names = pasteboard
            .types()
            .map(|types| {
                types
                    .to_vec()
                    .into_iter()
                    .map(|value| value.to_string())
                    .collect::<Vec<_>>()
            })
            .unwrap_or_default();
        let transient = TRANSIENT_TYPES
            .iter()
            .any(|marker| type_names.iter().any(|value| value == marker));
        let concealed = CONCEALED_TYPES
            .iter()
            .any(|marker| type_names.iter().any(|value| value == marker));
        let source_type = NSString::from_str(SOURCE_TYPE);
        let source_bundle_id = pasteboard
            .stringForType(&source_type)
            .map(|value| value.to_string())
            .filter(|value| !value.trim().is_empty());

        let mut file_paths = Vec::new();
        if let Some(items) = pasteboard.pasteboardItems() {
            for item in items.to_vec() {
                let Some(value) = item.stringForType(unsafe { NSPasteboardTypeFileURL }) else {
                    continue;
                };
                let Ok(url) = url::Url::parse(&value.to_string()) else {
                    continue;
                };
                if let Ok(path) = url.to_file_path() {
                    file_paths.push(path.to_string_lossy().into_owned());
                }
            }
        }
        if !file_paths.is_empty() {
            return Ok(Some((
                change_count,
                PasteboardSnapshot {
                    kind: PasteboardItemKind::Files,
                    text: None,
                    html: None,
                    bytes: None,
                    media_type: None,
                    file_paths: Some(file_paths),
                    source_bundle_id,
                    transient,
                    concealed,
                },
            )));
        }

        let fallback_text = pasteboard
            .stringForType(unsafe { NSPasteboardTypeString })
            .map(|value| value.to_string())
            .filter(|value| !value.is_empty());

        for (pasteboard_type, kind, media_type) in [
            (
                unsafe { NSPasteboardTypePDF },
                PasteboardItemKind::Pdf,
                "application/pdf",
            ),
            (
                unsafe { NSPasteboardTypePNG },
                PasteboardItemKind::Image,
                "image/png",
            ),
            (
                unsafe { NSPasteboardTypeTIFF },
                PasteboardItemKind::Image,
                "image/tiff",
            ),
        ] {
            if let Some(data) = pasteboard.dataForType(pasteboard_type) {
                return Ok(Some((
                    change_count,
                    PasteboardSnapshot {
                        kind,
                        text: fallback_text.clone(),
                        html: None,
                        bytes: Some(data.to_vec()),
                        media_type: Some(media_type.to_string()),
                        file_paths: None,
                        source_bundle_id,
                        transient,
                        concealed,
                    },
                )));
            }
        }

        if let Some(html) = pasteboard.stringForType(unsafe { NSPasteboardTypeHTML }) {
            return Ok(Some((
                change_count,
                PasteboardSnapshot {
                    kind: PasteboardItemKind::Html,
                    text: fallback_text,
                    html: Some(html.to_string()),
                    bytes: None,
                    media_type: Some("text/html".to_string()),
                    file_paths: None,
                    source_bundle_id,
                    transient,
                    concealed,
                },
            )));
        }

        for (pasteboard_type, media_type) in [
            (unsafe { NSPasteboardTypeRTF }, "text/rtf"),
            (unsafe { NSPasteboardTypeRTFD }, "text/rtfd"),
        ] {
            if let Some(data) = pasteboard.dataForType(pasteboard_type) {
                return Ok(Some((
                    change_count,
                    PasteboardSnapshot {
                        kind: PasteboardItemKind::RichText,
                        text: fallback_text.clone(),
                        html: None,
                        bytes: Some(data.to_vec()),
                        media_type: Some(media_type.to_string()),
                        file_paths: None,
                        source_bundle_id,
                        transient,
                        concealed,
                    },
                )));
            }
        }

        Ok(fallback_text.map(|text| {
            (
                change_count,
                PasteboardSnapshot {
                    kind: PasteboardItemKind::Text,
                    text: Some(text),
                    html: None,
                    bytes: None,
                    media_type: None,
                    file_paths: None,
                    source_bundle_id,
                    transient,
                    concealed,
                },
            )
        }))
    })
}
